### ISSUE TITLE
SigMgr::stNULL does not match NDN specifications

### ISSUE THREAD

**Issue by yoursunny** [pollere/DCT#2]
In [SignatureType assigned numbers](https://redmine.named-data.net/projects/ndn-tlv/wiki/SignatureType), Null signature was assigned the number `200` (decimal) on 2020-06-19.
DCT should use the officially assigned SignatureType number for Null signature.

https://github.com/pollere/DCT/blob/ef498fd4277c21f9379de7a05c9fe804a8c82ac3/include/dct/sigmgrs/sigmgr.hpp#L68-L73

**Comment by kmnichols** [comment]
This doesn't mean what you think it does. It's used to denote a NULL signature manager NOT a signature. That number and signature should NEVER be in a packet. In sigmgr_null.hpp, the comment header:

 * SigMgr Null provides a signing and validation methods that do nothing.
 * This is specifically provided for cert distribution and should not be
 * used otherwise (i.e., if you don't know why you are using this, don't!).
 
At the link you provided, the Null Signature Type is expressly described as "Empty signature for testing and experimentation" which is absolutely not the intent of SigMgrNULL at all. It is used to keep from changing the signature of a cert that is already signed.

**Comment by yoursunny** [comment]
> This doesn't mean what you think it does. It's used to denote a NULL signature manager NOT a signature.

This contradicts the comment directly above the code, which labels these constants as SigTypes and indicates that they should match NDN assigned numbers.

**Comment by kmnichols** [comment]
I'm not sure where you are finding the words "should match NDN assigned numbers" There is the above-cited comment in sigmgr_null.hpp. There is a not about the "'null' signer (no signature added to data)" in sigmgr.hpp. Again, that "type" never goes on the wire. The only reason for compatibility with NDN assigned numbers is to avoid any conflicts.
